# pls refer https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
name: ❓ Question 
description: File a Question
title: "[Question]: "
labels: [Type/Question]
body:
  - type: dropdown
    id: area-name
    attributes:
      label: Area
      description: Choose the Area you are reporting the question against
      options:
        - Area/Compiler (Language and Compiler FE)
        - Area/Runtime (jBallerina Runtime)
        - Area/StandardLibrary (Standard Library Modules) 
        - Area/DeveloperTools (VSCode, Test Framework, Debugger, Central, Package API)
        - Area/LanguageSupport (LS, Compiler APIs)
        - Area/Documentation (Web Site, API Docs, BBEs)
        - Area/Other (Any other area  which is not listed here)
    validations:
      required: true
  - type: input
    id: additional-labels
    attributes:
      label: Additional Labels
      description: >
        List down additional area tags as comma seperated values. For example: http, websub, debugger, central    
  - type: textarea
    id: description
    attributes:
      label: Description of the question
      description: Question details
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Ballerina Version or the component/module version
      description: Any other valuable information.
      placeholder: Ballerina Version and other related module versions     
