on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            var body = context.payload.issue.body
            var words = body.split(" ");
            console.log(words)
            for (var i = 0; i < words.length - 1; i++) {
                var word = words[i]
                var label1 = "";
                var label2 = "";
                if(word.startsWith('Name\n\nArea/')) {
                  label1 = word.substring(6) 
                  console.log(label1)
                    
                  break 
                }
                if(word.startsWith('Labels\n\n')) {
                  label2 = word.substring(6) 
                  console.log(label2)
                }
                github.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: [label1, label2]
                     })
            }
